[workspace]
members = [
    "crates/greentic-interfaces",
    "crates/greentic-interfaces-wasmtime",
]
resolver = "2"

[workspace.package]
license = "MIT"
edition = "2021"
authors = ["Greentic.ai"]
repository = "https://github.com/greentic-ai/greentic-interfaces"

[workspace.dependencies]
anyhow = "1"
greentic-types = { version = "0.1"}
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[patch.crates-io]
greentic-interfaces = { path = "crates/greentic-interfaces" }
