[package]
name = "component-describe"
version.workspace = true
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.47", default-features = false, features = ["macros", "realloc"] }
